import { defineConfig } from "cspell";

export default defineConfig({
  dictionaries: ["css", "html", "node", "npm", "typescript"],
  ignorePaths: ["pnpm-lock.yaml"],
  language: "en",
  useGitignore: true,
  words: [
    "antfu",
    "autodocs",
    "bradlc",
    "clsx",
    "daisyui",
    "dbaeumer",
    "esbenp",
    "esbuild",
    "gitzy",
    "iconify",
    "jiti",
    "knip",
    "lefthook",
    "lockb",
    "lucide",
    "noreferrer",
    "nvmrc",
    "oxfmt",
    "oxfmtrc",
    "Parens",
    "prefersdark",
    "tailwindcss",
    "tanstack",
    "tiged",
    "turborepo",
    "typecheck",
    "unrs",
    "vite",
    "vitest",
    "zustand",
  ],
});
