name: Install
description: Install everything for the repo

runs:
  using: composite
  steps:
    - name: 🏗 Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.1

    - name: 🏗 Setup bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-

    - name: 📦 Install ni
      run: bun install --global @antfu/ni
      shell: bash

    - name: 📦 Install deps
      run: ni
      shell: bash
