name: Install
description: Install everything for the repo

inputs:
  bun-version:
    description: Version of bun to use
    default: latest

runs:
  using: composite
  steps:
    - name: 🏗 Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 🏗 Setup bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-

    - name: 📦 Install deps
      run: bun install
      shell: bash
