name: preview

on: [deployment_status]

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: 🏗 Setup Repository
        uses: actions/checkout@v7

      - name: 📦 Install
        uses: ./.github/actions/install

      - name: 📦 Install Playwright Deps
        run: pnpm playwright install --with-deps

      - name: ✅ e2e
        run: pnpm turbo e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
